In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
ones = np.ones(3) 
zeros = np.zeros(3)
random = np.random.random(3)


In [4]:
data = np.array([1,2])
ones = np.ones(2)


In [5]:
data + ones

array([2., 3.])

In [6]:
data - ones 


array([0., 1.])

In [7]:

data * ones

array([1., 2.])

In [8]:

data / ones

array([1., 2.])

In [9]:
data * 1.6

array([1.6, 3.2])

In [10]:
data = np.array([1,2,3])
data 


array([1, 2, 3])

In [11]:
data[0]

1

In [12]:
data[1]

2

In [13]:
data[0:2]

array([1, 2])

In [14]:
data[1:]

array([2, 3])

In [15]:
data.max() 

3

In [16]:
data.min() 

1

In [17]:
data.sum() 

6

In [18]:
data = np.array([[1,2],[3,4]])

In [19]:
np.ones((3,2)) 


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:

np.zeros((3,2))  

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:

np.random.random((3,2))  

array([[0.51531524, 0.1560172 ],
       [0.81978777, 0.66275094],
       [0.13689725, 0.13922723]])

In [22]:
data = np.array([[1,2], [3,4]])
ones = np.ones((2,2))
data + ones


array([[2., 3.],
       [4., 5.]])

In [23]:
data = np.array([[1,2], [3,4], [5,6]])
ones_row = np.ones(2)
data + ones_row


array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [24]:
data = np.array([1,2,3])
powers_of_ten = np.array([[1,10], [100, 1000], [10000, 100000]])
data.dot(powers_of_ten)


array([ 30201, 302010])

In [27]:
data = np.array([[1,2], [3,4], [5,6]])

In [28]:
data[0,1]   

2

In [30]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [31]:
data[0:2,0] 

array([1, 3])

In [32]:
data.max() 

6

In [33]:
data.min() 

1

In [34]:
data.sum() 

21

In [35]:
data.max(axis=0) 

array([5, 6])

In [36]:
data.max(axis=1) 

array([2, 4, 6])

In [37]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
data = np.array(range(1,7)) 
data

array([1, 2, 3, 4, 5, 6])

In [39]:
data.reshape(2,3) 

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
data.reshape(3,2)  

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
data = ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
data

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [43]:
np.ones((4,3,2)) 

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [44]:

np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [45]:

np.random.random((4,3,2))


array([[[0.79219714, 0.21912695],
        [0.69919165, 0.02763112],
        [0.69262582, 0.27130506]],

       [[0.16288549, 0.73312012],
        [0.11042546, 0.91072806],
        [0.9111045 , 0.00728662]],

       [[0.24011129, 0.90559748],
        [0.66933946, 0.9545413 ],
        [0.60900562, 0.77328624]],

       [[0.05278394, 0.40684398],
        [0.1936529 , 0.89040311],
        [0.65294197, 0.8581585 ]]])

In [46]:
predictions = np.ones(3)
labels = np.array([1,2,3])
n=predictions.shape[0] 

error = 1/n * np.sum(np.square(predictions - labels))
error


1.6666666666666665